#python3 -m mio cha23-iso-cpu-read --ant_num_cores 1-6 --ant_mem_numa 3 --ant stream --ant_writefrac 0 --ant_inst_size 64 --ant_duration 100 --disable_prefetch --stats;
#python3 -m mio cha23-iso-cpu-write --ant_num_cores 1-6 --ant_mem_numa 3 --ant stream --ant_writefrac 50 --ant_inst_size 64 --ant_duration 100 --disable_prefetch --stats;
python3 -m mio cha23-iso-io-write --fio --fio_mem_numa 3 --fio_cpus 3,7 --fio_writefrac 0 --fio_iosize $((8*1024*1024)) --fio_iodepth 64 --fio_num_ssds 4 --fio_duration 100 --disable_prefetch --stats;
python3 -m mio cha23-iso-io-write-small --fio --fio_mem_numa 3 --fio_cpus 3,7 --fio_writefrac 0 --fio_iosize $((4*1024)) --fio_iodepth 1 --fio_num_ssds 1 --fio_duration 100 --disable_prefetch --stats;

python3 -m mio cha23-antread-iowritesmall --ant_num_cores 1-6 --ant_mem_numa 3 --ant stream --ant_writefrac 0 --ant_inst_size 64 --ant_duration 100 --fio --fio_mem_numa 3 --fio_cpus 3,7 --fio_writefrac 0 --fio_iosize $((4*1024)) --fio_iodepth 1 --fio_num_ssds 1 --sync_durations --disable_prefetch --stats
python3 -m mio cha23-antwrite-iowritesmall --ant_num_cores 1-6 --ant_mem_numa 3 --ant stream --ant_writefrac 50 --ant_inst_size 64 --ant_duration 100 --fio --fio_mem_numa 3 --fio_cpus 3,7 --fio_writefrac 0 --fio_iosize $((4*1024)) --fio_iodepth 1 --fio_num_ssds 1 --sync_durations --disable_prefetch --stats

python3 -m mio cha23-antread-iowrite --ant_num_cores 1-6 --ant_mem_numa 3 --ant stream --ant_writefrac 0 --ant_inst_size 64 --ant_duration 100 --fio --fio_mem_numa 3 --fio_cpus 3,7 --fio_writefrac 0 --fio_iosize $((8*1024*1024)) --fio_iodepth 64 --fio_num_ssds 4 --sync_durations --disable_prefetch --stats
python3 -m mio cha23-antwrite-iowrite --ant_num_cores 1-6 --ant_mem_numa 3 --ant stream --ant_writefrac 50 --ant_inst_size 64 --ant_duration 100 --fio --fio_mem_numa 3 --fio_cpus 3,7 --fio_writefrac 0 --fio_iosize $((8*1024*1024)) --fio_iodepth 64 --fio_num_ssds 4 --sync_durations --disable_prefetch --stats